---

- name: get host ip address
  getent:
    database: hosts
    key: "{{ inventory_hostname }}"
  delegate_to: localhost

- name: reboot into rescue mode
  include_tasks: rescue.yml

- name: attempt to gather facts
  setup:
  register: setup_status

- fail:
    msg: "Failed to gather facts for {{ inventory_hostname }}, something must have gone wrong."
  when: setup_status.unreachable is defined

- name: clean up before install
  block:
    - name: unmount disks
      mount:
        path: /mnt
        state: unmounted
    - name: clean up lvm data
      script: clean-lvm.sh
    - name: clean up raid arrays
      script: clean-md.sh
    - name: wipe signatures from devices
      command: "wipefs --all --force {{ item }}"
      loop: "{{ hetzner_devices }}"

- name: run installimage
  include_tasks: installimage.yml

# This currently only works with the defaults
- name: configure partitions
  script: partitions.sh

- name: reboot into installed system
  include_tasks: reboot.yml

- name: remove old key from known_hosts
  known_hosts:
    name: "{{ inventory_hostname }}"
    state: absent
  delegate_to: localhost

