---

- name: reboot server
  reboot:
    reboot_timeout: "{{ hetzner_reboot_timeout }}"
  register: reboot_result
  ignore_unreachable: True

- meta: clear_host_errors

- name: reset server
  local_action:
    module: uri
    url: "{{ hetzner_robot_address }}/reset/{{ getent_hosts|list|first }}"
    method: POST
    body:
      type: hw
    status_code: 200
  when: not reboot_result['changed']

- name: waiting for rescue mode
  local_action:
    module: wait_for
    host: "{{ inventory_hostname }}"
    port: 22
    delay: 30
    sleep: 5
    timeout: "{{ hetzner_reboot_timeout }}"

