---

# This task activates rescue mode and reboots the server.

- name: check if we are already in rescue mode
  stat:
    path: /root/.oldroot/nfs
  register: rescue_oldroot

- name: activate rescue mode
  uri:
    url: "{{ hetzner_robot_address }}/boot/{{ getent_hosts|list|first }}/rescue"
    method: POST
    body:
      os: linux
      arch: 64
      authorized_key: "{{ ssh_key_fingerprint }}"
    status_code:
      - 200
      - 409 # rescue mode already activated
  when: not rescue_oldroot.stat.exists
  delegate_to: localhost

- name: include reboot tasks
  include: reboot.yml
  when: not rescue_oldroot.stat.exists

